In [1]:
import pandas as pd
import numpy as np

# Useful Pandas DF Toolkit

#### Series.str.split(pat=None, n=-1, expand=False)
Splits a string Series(col name of df) into substrings.

pat = delimiter specifying how to split (default is ' ').

n = # of splits; None, 0 or -1 will split everything.

expand = True (optional - returns a df with a separate col per split, new col names will be int not string!).

https://www.geeksforgeeks.org/python-pandas-split-strings-into-two-list-columns-using-str-split/

#### df.rename(columns={'Old Col 1': 'New Col 1', 'Old Col 2' : 'New Col 2'}, inplace= True/False) 
Renames a column or row

inplace = modify the df directly (True) / do not modify original df (False)

#### df.insert(loc, column, value)
loc = column location
column = label of the inserted column
value = Scalar, Series, or Array-like (column from different df)

# CCLE Loading

In [2]:
CCLE = pd.read_csv('Edit Data\Edit_CCLE.csv')
print (CCLE.columns)
print ('Shape =', CCLE.shape)

Index(['Unnamed: 0', '1433BETA', '1433EPSILON', '1433ZETA', '4EBP1',
       '4EBP1_pS65', '4EBP1_pT37T46', '4EBP1_pT70', '53BP1', 'ARAF_pS299',
       ...
       'TUBERIN_pT1462', 'VAV1', 'VEGFR2', 'VHL', 'XBP1', 'XRCC1', 'YAP',
       'YAP_pS127', 'YB1', 'YB1_pS102'],
      dtype='object', length=215)
Shape = (899, 215)

In [3]:
# Splitting and Renaming Columns
Split = CCLE["Unnamed: 0"].str.split("_", n = 1, expand = True) #Split the Column Name
CCLE.insert(1, "Sample", Split[0]) 
CCLE.insert(2, "Cancer Type", Split[1])
CCLE.drop("Unnamed: 0", axis = 1, inplace = True)
CCLE.head()

,Sample,Cancer Type,1433BETA,1433EPSILON,1433ZETA,4EBP1,4EBP1_pS65,4EBP1_pT37T46,4EBP1_pT70,53BP1,...,TUBERIN_pT1462,VAV1,VEGFR2,VHL,XBP1,XRCC1,YAP,YAP_pS127,YB1,YB1_pS102
0,DMS53,LUNG,-0.104888,0.060414,0.309068,-0.075506,0.230359,0.198304,-0.030541,0.455889,...,-0.099433,-0.486715,-1.147858,0.133876,-0.075812,-0.144388,-1.090303,-2.109324,0.178104,0.246541
1,SW1116,LARGE_INTESTINE,0.358504,-0.180291,-0.041237,-0.286629,-0.877406,-1.026948,-0.462761,-0.011197,...,-0.109777,0.349330,0.770148,0.984297,-0.168138,-0.004905,0.189294,-0.283593,0.255972,-0.121134
2,NCIH1694,LUNG,0.028738,0.071902,-0.094847,0.285069,1.321551,0.620703,-0.439484,0.195007,...,0.154344,-0.478189,-1.185530,1.273013,-0.240413,0.476633,-1.367465,-2.525695,-0.137880,-0.451282
3,P3HR1,HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,0.120039,-0.066802,-0.128007,-0.552081,-0.292428,-1.415935,-0.138858,-0.066122,...,0.040106,5.923830,-3.893832,-2.499188,0.632758,0.025639,-1.189180,-3.056863,0.025997,-0.465205
4,HUT78,HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,-0.268997,-0.060281,-0.137881,-0.398729,-0.095622,-0.533905,0.054245,-0.573022,...,-0.466919,5.475880,-0.561973,-0.500953,-0.261494,0.358679,-0.951686,-3.247388,-0.151424,-0.145426

# MCLP Loading

In [4]:
MCLP = pd.read_csv('Edit Data\Edit_MCLP.csv')
print (MCLP.columns)
print ('Shape =', MCLP.shape)

Index(['Sample_Name', '1433EPSILON', '4EBP1', '4EBP1_pS65', '4EBP1_pT37T46',
       '53BP1', 'ACC_pS79', 'ACC1', 'AKT', 'AKT_pS473',
       ...
       'FAK_pY925', 'GAB2_pY452', 'JAK1', 'JUNB', 'NEUROPILIN1', 'NUR77',
       'PKCDELTA_pT507', 'SMAD6', 'TCF4', 'TIF1ALPHA'],
      dtype='object', length=453)
Shape = (651, 453)

In [6]:
# Renaming and inserting new columns
MCLP.rename(columns = {'Sample_Name' : 'Sample'}, inplace = True) #rename Sample_Name to Sample
MCLP.insert(1, "Cancer Type", None) #insert Cancer_Type Column with None values
MCLP.head()

,Sample,Cancer Type,1433EPSILON,4EBP1,4EBP1_pS65,4EBP1_pT37T46,53BP1,ACC_pS79,ACC1,AKT,...,FAK_pY925,GAB2_pY452,JAK1,JUNB,NEUROPILIN1,NUR77,PKCDELTA_pT507,SMAD6,TCF4,TIF1ALPHA
0,CAOV3,None,-0.206840,-0.55301,-0.16965,0.53459,-0.081414,-1.02280,0.18944,0.295060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HOC1,None,-0.126100,0.69268,0.56197,1.83740,-0.838290,-1.16030,0.40530,0.072127,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HOC7,None,-0.148280,0.36835,0.64182,1.41550,-0.776860,-0.70407,0.55247,0.301970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HOC8,None,-0.047959,0.28927,0.50839,1.54540,-0.601450,-1.12940,0.86079,-1.069400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ZR75T,None,0.165510,0.59128,1.40970,1.54460,-0.599300,0.75610,1.30000,0.504230,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
# Deesignating Cancer Types based on CCLE Classifications
sMCLP = len(MCLP)
sCCLE = len(CCLE)

# Nested code below iterates through the MCLP Sample column and compares it to every the CCLE Sample column
# If the values match, the MCLP Cancer Type will be replaced with the CCLE Cancer Type
for i in range(sMCLP): 
    for j in range(sCCLE):
        if MCLP.iloc[i, 0] == CCLE.iloc[j, 0]:
            MCLP.iloc[i, 1] = CCLE.iloc[j, 1]
            break #allows exiting of the inner for loop
        else:
            MCLP.iloc[i, 1] = "Undefined"
MCLP.head()

,Sample,Cancer Type,1433EPSILON,4EBP1,4EBP1_pS65,4EBP1_pT37T46,53BP1,ACC_pS79,ACC1,AKT,...,FAK_pY925,GAB2_pY452,JAK1,JUNB,NEUROPILIN1,NUR77,PKCDELTA_pT507,SMAD6,TCF4,TIF1ALPHA
0,CAOV3,OVARY,-0.206840,-0.55301,-0.16965,0.53459,-0.081414,-1.02280,0.18944,0.295060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HOC1,Undefined,-0.126100,0.69268,0.56197,1.83740,-0.838290,-1.16030,0.40530,0.072127,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HOC7,Undefined,-0.148280,0.36835,0.64182,1.41550,-0.776860,-0.70407,0.55247,0.301970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HOC8,Undefined,-0.047959,0.28927,0.50839,1.54540,-0.601450,-1.12940,0.86079,-1.069400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ZR75T,Undefined,0.165510,0.59128,1.40970,1.54460,-0.599300,0.75610,1.30000,0.504230,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# TCGA Loading

In [6]:
TCGA = pd.read_csv('Edit Data\Edit_TCGA-PANCAN32.csv')
print (TCGA.columns)
print ('Shape =', TCGA.shape)

Index(['Sample_ID', 'Cancer_Type', 'Sample_Type', '1433EPSILON', '4EBP1',
       '4EBP1_pS65', '4EBP1_pT37T46', '53BP1', 'ACC_pS79', 'ACC1',
       ...
       'PARPAB3', 'THYMIDILATESYNTHASE', 'TTF1', 'CHROMOGRANINANTERM', 'CK5',
       'NAPSINA', 'P63', 'RET_pY905', 'SYNAPTOPHYSIN', 'ALPHACATENIN'],
      dtype='object', length=261)
Shape = (7694, 261)

In [7]:
print (TCGA['Sample_Type'].unique())
TCGA.rename(columns = {'Sample_ID' : 'Sample', 'Cancer_Type' : 'Cancer Type'}, inplace = True) #rename Sample_Name to Sample
TCGA.head(2)

['Primary' 'Metastatic']

,Sample,Cancer Type,Sample_Type,1433EPSILON,4EBP1,4EBP1_pS65,4EBP1_pT37T46,53BP1,ACC_pS79,ACC1,...,PARPAB3,THYMIDILATESYNTHASE,TTF1,CHROMOGRANINANTERM,CK5,NAPSINA,P63,RET_pY905,SYNAPTOPHYSIN,ALPHACATENIN
0,TCGA-AO-A1KP-01A-21-A17I-20,BRCA,Primary,0.11304,0.00350,-0.150460,0.26271,-0.68908,-0.97899,-1.23550,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TCGA-FG-8191-01A-11-A29Z-20,LGG,Primary,0.19884,-0.73442,-0.193490,-0.38683,-0.80777,-0.70958,-0.78887,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.62423
2,TCGA-34-5232-01A-22-2194-20,LUSC,Primary,-0.21886,0.44996,0.005231,0.38994,-0.88473,-0.22324,-0.32914,...,0.45607,0.003855,1.0009,0.35940,0.021303,-0.20533,0.84349,-0.17617,0.16572,NaN
3,TCGA-EV-5903-01A-21-A39O-20,KIRP,Primary,0.21520,-0.33630,-0.263290,-0.82751,-1.04460,0.53671,0.56257,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TCGA-49-4514-01A-22-2190-20,LUAD,Primary,0.08883,0.74123,0.263190,1.29900,-1.69780,-0.63225,-1.01400,...,0.70409,0.394790,1.9965,0.15326,-0.236860,0.27223,0.22516,-0.31620,-0.15950,NaN

# Unifying Datasets
The CCLE dataset will be used to unify the data as it has the lowest number of protein expression data in the RPPA experiment.

In [8]:
# Determining what features(columns) match across all datasets 
a = list(CCLE.columns.values)
b = list(MCLP.columns.values)
c = list(TCGA.columns.values)

def uniformity(x, y, z):
    uniform_list = []
    for i in x:
        #use in function to detect which items are available
        if i in y and i in z:
            uniform_list.append(i)
    return uniform_list     

u = uniformity(a, b, c)

In [9]:
uCCLE = CCLE[u].copy(deep = True) #run a deep copy just incase modification of original list could occur.
print ('uCCLE Shape =', uCCLE.shape)
uCCLE.head()

uCCLE Shape = (899, 193)

,Sample,Cancer Type,1433BETA,1433EPSILON,1433ZETA,4EBP1,4EBP1_pS65,4EBP1_pT37T46,4EBP1_pT70,53BP1,...,TTF1,TUBERIN,TUBERIN_pT1462,VEGFR2,XBP1,XRCC1,YAP,YAP_pS127,YB1,YB1_pS102
0,DMS53,LUNG,-0.104888,0.060414,0.309068,-0.075506,0.230359,0.198304,-0.030541,0.455889,...,0.994481,-0.236701,-0.099433,-1.147858,-0.075812,-0.144388,-1.090303,-2.109324,0.178104,0.246541
1,SW1116,LARGE_INTESTINE,0.358504,-0.180291,-0.041237,-0.286629,-0.877406,-1.026948,-0.462761,-0.011197,...,0.860255,-0.446645,-0.109777,0.770148,-0.168138,-0.004905,0.189294,-0.283593,0.255972,-0.121134
2,NCIH1694,LUNG,0.028738,0.071902,-0.094847,0.285069,1.321551,0.620703,-0.439484,0.195007,...,-0.225280,0.465112,0.154344,-1.185530,-0.240413,0.476633,-1.367465,-2.525695,-0.137880,-0.451282
3,P3HR1,HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,0.120039,-0.066802,-0.128007,-0.552081,-0.292428,-1.415935,-0.138858,-0.066122,...,0.698834,0.704027,0.040106,-3.893832,0.632758,0.025639,-1.189180,-3.056863,0.025997,-0.465205
4,HUT78,HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,-0.268997,-0.060281,-0.137881,-0.398729,-0.095622,-0.533905,0.054245,-0.573022,...,-0.260483,-0.130782,-0.466919,-0.561973,-0.261494,0.358679,-0.951686,-3.247388,-0.151424,-0.145426

In [10]:
uMCLP = MCLP[u].copy(deep = True) #run a deep copy just incase modification of original list could occur.
print ('uMCLP Shape =', uMCLP.shape)
uMCLP.head()

uMCLP Shape = (651, 193)

,Sample,Cancer Type,1433BETA,1433EPSILON,1433ZETA,4EBP1,4EBP1_pS65,4EBP1_pT37T46,4EBP1_pT70,53BP1,...,TTF1,TUBERIN,TUBERIN_pT1462,VEGFR2,XBP1,XRCC1,YAP,YAP_pS127,YB1,YB1_pS102
0,CAOV3,None,-0.133690,-0.206840,-0.41885,-0.55301,-0.16965,0.53459,-0.348580,-0.081414,...,NaN,-0.263360,-0.27455,0.17733,0.075714,0.266260,-0.251500,0.34643,0.46232,0.26558
1,HOC1,None,-0.779200,-0.126100,0.11505,0.69268,0.56197,1.83740,0.035815,-0.838290,...,NaN,0.046398,0.18650,0.48545,0.162450,0.087729,0.131330,0.43243,0.55686,0.44792
2,HOC7,None,-0.071738,-0.148280,-0.19246,0.36835,0.64182,1.41550,0.139840,-0.776860,...,NaN,0.183330,0.26049,0.08451,0.029996,0.425700,0.037708,0.95869,0.13301,0.41950
3,HOC8,None,-0.336260,-0.047959,-0.56448,0.28927,0.50839,1.54540,0.074483,-0.601450,...,NaN,0.690840,0.74657,-0.38538,0.195110,0.536290,-0.273490,0.39835,0.27822,0.43321
4,ZR75T,None,0.147470,0.165510,0.46674,0.59128,1.40970,1.54460,0.441590,-0.599300,...,NaN,-0.112940,-0.55694,-0.73703,-0.295320,-0.537540,-0.941330,-1.36380,-0.45702,0.47751

In [17]:
uTCGA = TCGA[u].copy(deep = True) #run a deep copy just incase modification of original list could occur.
print ('uTCGA Shape =', uTCGA.shape)
uTCGA.head(3)

uTCGA Shape = (7694, 193)

,Sample,Cancer Type,1433BETA,1433EPSILON,1433ZETA,4EBP1,4EBP1_pS65,4EBP1_pT37T46,4EBP1_pT70,53BP1,...,TTF1,TUBERIN,TUBERIN_pT1462,VEGFR2,XBP1,XRCC1,YAP,YAP_pS127,YB1,YB1_pS102
0,TCGA-AO-A1KP-01A-21-A17I-20,BRCA,0.44477,0.11304,0.40319,0.00350,-0.150460,0.26271,0.099322,-0.68908,...,NaN,-0.50123,0.11390,0.25187,-0.048907,0.031347,0.47133,0.36057,-0.004762,-0.03641
1,TCGA-FG-8191-01A-11-A29Z-20,LGG,0.28207,0.19884,-0.25618,-0.73442,-0.193490,-0.38683,0.044093,-0.80777,...,NaN,0.35894,0.25487,-0.97129,2.174300,-0.685800,-0.31786,-1.09900,-0.234710,0.17666
2,TCGA-34-5232-01A-22-2194-20,LUSC,-0.12796,-0.21886,0.48245,0.44996,0.005231,0.38994,0.428090,-0.88473,...,1.0009,-0.18882,-0.21915,-0.27379,-0.647680,0.107580,0.11522,0.22367,-0.124470,0.14995

In [82]:
Indication_Array = CCLE["Cancer Type"].unique()
Indication_List = Indication_Array.tolist()
print (Indication_List)

['LUNG', 'LARGE_INTESTINE', 'HAEMATOPOIETIC_AND_LYMPHOID_TISSUE', 'URINARY_TRACT', 'BONE', 'SKIN', 'LIVER', 'PLEURA', 'OVARY', 'OESOPHAGUS', 'ENDOMETRIUM', 'FIBROBLAST', 'CENTRAL_NERVOUS_SYSTEM', 'SOFT_TISSUE', 'PANCREAS', 'AUTONOMIC_GANGLIA', 'STOMACH', 'KIDNEY', 'BREAST', 'UPPER_AERODIGESTIVE_TRACT', 'THYROID', 'SALIVARY_GLAND', 'BILIARY_TRACT', 'PROSTATE']

In [1]:
# Chat gpt was used to classify the TCGA indications into the 

{'ACC' : 'ADRENAL', 
'BLCA' : 'URINARY_TRACT',
'BRCA' : 'BREAST',
'CESC' : 'CERVICAL',
'CHOL' : 'BILIARY_TRACT',
'COAD' : 'LARGE_INTESTINE',
'DLBC' : 'HAEMATOPOIETIC_AND_LYMPHOID_TISSUE',
'ESCA' : 'OESOPHAGUS',
'GBM' : 'CENTRAL_NERVOUS_SYSTEM',
'HNSC' : 'UPPER_AERODIGESTIVE_TRACT',
'KICH' : 'KIDNEY',
'KIRC' : 'KIDNEY',
'KIRP' : 'KIDNEY',
'LGG' : 'CENTRAL_NERVOUS_SYSTEM',
'LIHC' : 'LIVER',
'LUAD' : 'LUNG',
'LUSC' : 'LUNG',
'MESO' : 'PLEURA',
'OV' : 'OVARY',
'PAAD' : 'PANCREAS',
'PCPG' : 'AUTONOMIC_GANGLIA',
'PRAD' : 'PROSTATE',
'READ' : 'LARGE_INTESTINE',
'SARC' : 'SOFT_TISSUE',
'SKCM' : 'SKIN',
'STAD' : 'STOMACH',
'TGCT' : 'TESTIS',
'THCA' : 'THYROID',
'THYM' : 'HAEMATOPOIETIC_AND_LYMPHOID_TISSUE',
'UCEC' : 'ENDOMETRIUM',
'UCS' : 'SOFT_TISSUE',
'UVM' : 'EYE'}